import React from 'react';
import { Link } from 'react-router-dom';
import { 
  Sun, 
  Zap, 
  BatteryCharging, 
  Building2, 
  Factory, 
  Compass, 
  ArrowRight, 
  CheckCircle2,
  Layers,
  ArrowDown
} from 'lucide-react';
import { useQuote } from '../context/QuoteContext';

export const SolutionsPage: React.FC = () => {
  const { openQuoteModal } = useQuote();

  return (
    <div className="space-y-0">
      {/* Page Header */}
      <section className="bg-slate-950 text-white py-16 sm:py-20 relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center max-w-3xl">
          <span className="inline-block bg-amber-500/20 text-amber-300 text-xs font-bold px-3 py-1 rounded-full mb-3 uppercase tracking-wider">
            Our Solar Solutions
          </span>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
            Comprehensive Solar Power Systems for Every Rooftop
          </h1>
          <p className="text-slate-300 text-sm sm:text-base mt-3">
            From grid-tied residential systems cutting domestic bills to multi-megawatt industrial EPC plants and hybrid battery storage.
          </p>
        </div>
      </section>

      {/* 1. On-Grid Solar System */}
      <section id="on-grid" className="py-16 sm:py-20 bg-white border-b border-slate-200 scroll-mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-4">
              <div className="inline-flex items-center gap-2 bg-amber-100 text-amber-900 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider">
                <Sun className="w-3.5 h-3.5 text-amber-600" />
                <span>01. On-Grid Solar System (Grid-Tied)</span>
              </div>
              <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
                Maximum Electricity Bill Reduction with Net-Metering
              </h2>
              <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
                An On-Grid solar system operates in direct synchronization with the UPPCL utility grid. Power generated by your solar modules directly runs your home or business loads during the day. Any excess solar units are automatically exported back to the grid via a bidirectional net-meter, earning electricity credits.
              </p>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900">
                  Ideal & Suitable For:
                </h4>
                <div className="flex flex-wrap gap-2 text-xs">
                  {['Independent Homes', 'Villas', 'Shops & Retail', 'Offices', 'Schools & Colleges', 'Hospitals', 'Factories'].map((item) => (
                    <span key={item} className="bg-white border border-slate-200 px-3 py-1 rounded-lg text-slate-700 font-medium">
                      ✓ {item}
                    </span>
                  ))}
                </div>
              </div>

              <div className="space-y-2 pt-2 text-xs text-slate-700">
                <p className="font-bold text-slate-900">Key Benefits:</p>
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Up to 90% electricity bill reduction</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Minimal maintenance (No battery replacement costs)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Full Net-Metering support with UPPCL</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Fast 3 to 4.5 years payback period</span>
                  </li>
                </ul>
              </div>

              <div className="pt-4 flex gap-3">
                <button
                  onClick={() => openQuoteModal({ solarRequirement: 'on-grid' })}
                  className="bg-amber-500 hover:bg-amber-600 text-white font-bold px-6 py-3 rounded-xl text-xs sm:text-sm cursor-pointer"
                >
                  Get On-Grid Quotation
                </button>
                <Link
                  to="/residential-solar"
                  className="px-5 py-3 rounded-xl border border-slate-300 text-slate-700 hover:bg-slate-50 font-semibold text-xs sm:text-sm"
                >
                  View Residential Sizing Matrix
                </Link>
              </div>
            </div>

            <div className="bg-slate-100 rounded-3xl overflow-hidden border border-slate-200 p-2 shadow-lg">
              <img
                src="https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=1000&q=80"
                alt="On-Grid Solar System"
                className="w-full h-80 sm:h-96 object-cover rounded-2xl"
              />
            </div>
          </div>
        </div>
      </section>

      {/* 2. Hybrid Solar System */}
      <section id="hybrid" className="py-16 sm:py-20 bg-slate-50 border-b border-slate-200 scroll-mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            
            {/* System Flow Diagram per workflow specification 4 */}
            <div className="order-2 lg:order-1 bg-white p-6 sm:p-8 rounded-3xl border border-slate-200 shadow-md">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-4 text-center">
                Interactive Power Flow Architecture
              </h4>

              <div className="flex flex-col items-center space-y-3">
                <div className="w-full max-w-sm bg-amber-50 border border-amber-300 rounded-xl p-3 text-center">
                  <div className="text-amber-700 font-bold text-xs uppercase">1. Solar Panels (Rooftop)</div>
                  <div className="text-[11px] text-slate-600">Generates clean DC Solar Electricity</div>
                </div>

                <ArrowDown className="w-5 h-5 text-amber-500" />

                <div className="w-full max-w-sm bg-purple-50 border border-purple-300 rounded-xl p-3 text-center">
                  <div className="text-purple-700 font-bold text-xs uppercase">2. Intelligent Hybrid Inverter</div>
                  <div className="text-[11px] text-slate-600">Converts DC to AC & manages Grid + Storage priority</div>
                </div>

                <div className="w-full max-w-sm grid grid-cols-2 gap-3">
                  <div className="bg-emerald-50 border border-emerald-300 rounded-xl p-3 text-center">
                    <div className="text-emerald-700 font-bold text-xs uppercase">3. Battery Bank</div>
                    <div className="text-[10px] text-slate-600">LiFePO4 Lithium Storage for night & power cuts</div>
                  </div>
                  <div className="bg-blue-50 border border-blue-300 rounded-xl p-3 text-center">
                    <div className="text-blue-700 font-bold text-xs uppercase">4. Utility Grid</div>
                    <div className="text-[10px] text-slate-600">Net-metering export & auxiliary backup</div>
                  </div>
                </div>

                <ArrowDown className="w-5 h-5 text-emerald-500" />

                <div className="w-full max-w-sm bg-slate-900 text-white rounded-xl p-3 text-center">
                  <div className="font-bold text-xs text-amber-400 uppercase">5. Continuous Home & Business Load</div>
                  <div className="text-[11px] text-slate-300">Uninterrupted power 24/7 with zero flicker</div>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-slate-100 text-center">
                <p className="text-xs text-slate-500">
                  Example: <strong>5 kW Hybrid Solar System</strong> powers lighting, fans, computers, TV, and 1.5 ton Inverter AC even during grid outages.
                </p>
              </div>
            </div>

            <div className="order-1 lg:order-2 space-y-4">
              <div className="inline-flex items-center gap-2 bg-purple-100 text-purple-900 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider">
                <BatteryCharging className="w-3.5 h-3.5 text-purple-600" />
                <span>02. Hybrid Solar System (Solar + Grid + Battery)</span>
              </div>
              <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
                Complete Bill Savings + 24/7 Power Security
              </h2>
              <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
                Suitable for customers requiring guaranteed electricity backup during local load shedding and voltage fluctuations, while simultaneously enjoying the high savings of an on-grid net-metering system.
              </p>

              <div className="space-y-2 text-xs text-slate-700">
                <p className="font-bold text-slate-900">Why Choose Hybrid?</p>
                <ul className="space-y-1.5">
                  <li className="flex items-start gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    <span>Eliminates expensive, noisy, and polluting diesel generators.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    <span>Smart battery priority: Charge batteries during daytime from free solar.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    <span>Advanced LiFePO4 batteries with 15+ year operational lifespan.</span>
                  </li>
                </ul>
              </div>

              <div className="pt-4 flex gap-3">
                <button
                  onClick={() => openQuoteModal({ solarRequirement: 'hybrid' })}
                  className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-6 py-3 rounded-xl text-xs sm:text-sm cursor-pointer"
                >
                  Enquire for Hybrid System
                </button>
                <Link
                  to="/battery-bess"
                  className="px-5 py-3 rounded-xl border border-slate-300 text-slate-700 hover:bg-slate-50 font-semibold text-xs sm:text-sm"
                >
                  Explore Battery Options
                </Link>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* 3. Off-Grid Solar */}
      <section id="off-grid" className="py-16 sm:py-20 bg-white border-b border-slate-200 scroll-mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-4">
              <div className="inline-flex items-center gap-2 bg-emerald-100 text-emerald-900 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider">
                <Zap className="w-3.5 h-3.5 text-emerald-600" />
                <span>03. Off-Grid Solar System</span>
              </div>
              <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
                100% Energy Independence Where Grid Power is Unavailable
              </h2>
              <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
                Where reliable utility grid electricity is unavailable or locations suffer from persistent power outages, an Off-Grid Solar System functions as your self-sufficient private power station.
              </p>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900">
                  Ideal Applications:
                </h4>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div className="flex items-center gap-2 text-slate-700 font-medium">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Farmhouses & Agricultural land</span>
                  </div>
                  <div className="flex items-center gap-2 text-slate-700 font-medium">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Remote locations & Highway resorts</span>
                  </div>
                  <div className="flex items-center gap-2 text-slate-700 font-medium">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Rural schools & Health centers</span>
                  </div>
                  <div className="flex items-center gap-2 text-slate-700 font-medium">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Independent telecom / pump sites</span>
                  </div>
                </div>
              </div>

              <div className="pt-2">
                <button
                  onClick={() => openQuoteModal({ solarRequirement: 'off-grid' })}
                  className="bg-slate-900 hover:bg-slate-800 text-white font-bold px-6 py-3 rounded-xl text-xs sm:text-sm cursor-pointer"
                >
                  Get Off-Grid Sizing Quote
                </button>
              </div>
            </div>

            <div className="bg-slate-100 rounded-3xl overflow-hidden border border-slate-200 p-2 shadow-lg">
              <img
                src="https://images.unsplash.com/photo-1548337138-e87d889cc369?auto=format&fit=crop&w=1000&q=80"
                alt="Off-Grid Solar System"
                className="w-full h-80 sm:h-96 object-cover rounded-2xl"
              />
            </div>
          </div>
        </div>
      </section>

      {/* 4 & 5. Commercial & Industrial Links */}
      <section className="py-16 sm:py-20 bg-slate-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center max-w-3xl mb-12">
          <span className="text-xs font-bold text-amber-400 uppercase tracking-wider block mb-2">
            Commercial & Industrial Scale
          </span>
          <h2 className="text-3xl sm:text-4xl font-black text-white">
            High-Capacity Turnkey Solar Plants (10 kW to 1 MW+)
          </h2>
          <p className="text-slate-300 text-sm sm:text-base mt-2">
            Engineered for corporate bottom lines with tax benefits and dramatic operational expenditure reduction.
          </p>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Commercial Box */}
          <div className="bg-slate-800/90 border border-slate-700 rounded-3xl p-8 flex flex-col justify-between">
            <div>
              <div className="w-12 h-12 rounded-2xl bg-blue-500/20 text-blue-400 flex items-center justify-center mb-4">
                <Building2 className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2">Commercial Solar</h3>
              <p className="text-xs text-slate-300 font-mono mb-4">10 kW | 20 kW | 30 kW | 50 kW | 75 kW | 100 kW+</p>
              <p className="text-xs text-slate-400 leading-relaxed mb-6">
                Tailored for Hotels, Hospitals, Schools, Warehouses, Cold Storage, Factories, Offices & Showrooms. Enjoy 40% accelerated tax depreciation and 3-4 year return on capital.
              </p>
            </div>
            <Link
              to="/commercial-solar"
              className="inline-flex items-center justify-center gap-2 py-3 px-4 bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold text-xs sm:text-sm rounded-xl transition-colors"
            >
              <span>Explore Commercial Solar Page</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Industrial Box */}
          <div className="bg-slate-800/90 border border-slate-700 rounded-3xl p-8 flex flex-col justify-between">
            <div>
              <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center mb-4">
                <Factory className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2">Industrial Solar EPC</h3>
              <p className="text-xs text-slate-300 font-mono mb-4">100 kW | 250 kW | 500 kW | 1 MW+</p>
              <p className="text-xs text-slate-400 leading-relaxed mb-6">
                Full 8-stage turnkey EPC execution: Site Survey, Load Analysis, Solar Design, Financial Proposal, Procurement, Installation, Testing & Commissioning, and Long-Term AMC.
              </p>
            </div>
            <Link
              to="/industrial-solar"
              className="inline-flex items-center justify-center gap-2 py-3 px-4 bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold text-xs sm:text-sm rounded-xl transition-colors"
            >
              <span>Explore Industrial EPC Process</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};
